### ISSUE TITLE
OAuth integration

### ISSUE THREAD

**Issue by promentol** [spencercarli/meteor-react-native-authentication#3]
Thank you for awesome work! Are you planning to add support for oauth Authentication like Facebook, Twitter and etc?

**Comment by spencercarli** [comment]
Hey @promentol! Other oauth providers are definitely on my road map.I just published a blog post about using Google for authentication. You can read it [here](https://medium.com/@spencer_carli/meteor-google-oauth-from-react-native-e30d146dfad6#.fw6p5xrn9) or check out the repo [here](https://github.com/spencercarli/react-native-meteor-google-oauth).

Facebook, Twitter, and others are on my roadmap but I found the Google one a bit tricky to write about. Before I dive into the other providers I'm trying to figure out a good system to manage everything - because what good is an broken example, right? Keep an eye out on Medium for updates in regards to future oauth tutorials!

**Comment by spencercarli** [comment]
Closing as this has been covered in the blog post. I may put together a guide on various auth providers in the future - if so it will have its own repo.
